Pass github token to arduino/setup-protoc action (#7699)
## What changed?
<!-- Describe what has changed in this PR -->
Pass Github token to `arduino/setup-protoc` action.

## Why?
<!-- Tell your future self why have you made these changes -->
Avoid rate limiting error:
```
Error: Error: API rate limit exceeded for 20.102.199.133. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

## How did you test it?
<!-- How have you verified this change? Tested locally? Added a unit
test? Checked in staging env? -->

## Potential risks
<!-- Assuming the worst case, what can be broken when deploying this
change to production? -->

## Documentation
<!-- Have you made sure this change doesn't falsify anything currently
stated in `docs/`? If significant
new behavior is added, have you described that in `docs/`? -->

## Is hotfix candidate?
<!-- Is this PR a hotfix candidate or does it require a notification to
be sent to the broader community? (Yes/No) -->