Print actual events in HistoryRequire helper (#6826)
## What changed?
<!-- Describe what has changed in this PR -->

Before

```
Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 5
        	Test:       	TestResetWorkflowTestSuite/TestResetWorkflowAfterTimeout
        	Messages:   	Length of expected(4) and actual(5) histories is not equal
```

After

```
Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 5
        	Test:       	TestResetWorkflowTestSuite/TestResetWorkflowAfterTimeout
        	Messages:   	Length of expected(4) and actual(5) histories is not equal - actual history: 
        	            	  1 WorkflowExecutionStarted
        	            	  2 WorkflowTaskScheduled
        	            	  3 WorkflowTaskStarted
        	            	  4 WorkflowTaskCompleted
        	            	  5 WorkflowExecutionCompleted
```

## Why?
<!-- Tell your future self why have you made these changes -->

Help understand why the length was different; without firing up a
debugger.

## How did you test it?
<!-- How have you verified this change? Tested locally? Added a unit
test? Checked in staging env? -->

## Potential risks
<!-- Assuming the worst case, what can be broken when deploying this
change to production? -->

## Documentation
<!-- Have you made sure this change doesn't falsify anything currently
stated in `docs/`? If significant
new behavior is added, have you described that in `docs/`? -->

## Is hotfix candidate?
<!-- Is this PR a hotfix candidate or does it require a notification to
be sent to the broader community? (Yes/No) -->